<a href="https://colab.research.google.com/github/dkuzzmin/DI-Bootcamp/blob/main/Week7/Day3/W7D3_XC_DC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Daily Challenge: Web Scraping And Data Visualization
1-5 exercises

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import seaborn as sns
from scipy import stats

In [4]:
df = pd.read_csv("adult.data", sep=',', names=[
    'age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status',
    'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss',
    'hours-per-week', 'native-country', 'income'
])

In [5]:
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64
 11  capital-loss    32561 non-null  int64
 12  hours-per-week  32561 non-null  int64
 13  native-country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [7]:
df['age'].sort_values()

12318    17
6312     17
30927    17
12787    17
25755    17
         ..
24043    90
32277    90
5104     90
8963     90
10210    90
Name: age, Length: 32561, dtype: int64

In [11]:
df['income'].unique()

array([' <=50K', ' >50K'], dtype=object)

In [14]:
df[['fnlwgt', 'education-num','capital-gain','capital-loss','hours-per-week']].describe()

             fnlwgt  education-num  capital-gain  capital-loss  hours-per-week
count  3.256100e+04   32561.000000  32561.000000  32561.000000    32561.000000
mean   1.897784e+05      10.080679   1077.648844     87.303830       40.437456
std    1.055500e+05       2.572720   7385.292085    402.960219       12.347429
min    1.228500e+04       1.000000      0.000000      0.000000        1.000000
25%    1.178270e+05       9.000000      0.000000      0.000000       40.000000
50%    1.783560e+05      10.000000      0.000000      0.000000       40.000000
75%    2.370510e+05      12.000000      0.000000      0.000000       45.000000
max    1.484705e+06      16.000000  99999.000000   4356.000000       99.000000

In [15]:
ndf = df[['fnlwgt', 'education-num','capital-gain','capital-loss','hours-per-week']]

In [16]:
scaler = MinMaxScaler()

df_normalized = pd.DataFrame(scaler.fit_transform(ndf), columns=ndf.columns)

print("Normalized Data:")
print(df_normalized)

Normalized Data:
         fnlwgt  education-num  capital-gain  capital-loss  hours-per-week
0      0.044302       0.800000      0.021740           0.0        0.397959
1      0.048238       0.800000      0.000000           0.0        0.122449
2      0.138113       0.533333      0.000000           0.0        0.397959
3      0.151068       0.400000      0.000000           0.0        0.397959
4      0.221488       0.800000      0.000000           0.0        0.397959
...         ...            ...           ...           ...             ...
32556  0.166404       0.733333      0.000000           0.0        0.377551
32557  0.096500       0.533333      0.000000           0.0        0.397959
32558  0.094827       0.533333      0.000000           0.0        0.397959
32559  0.128499       0.533333      0.000000           0.0        0.193878
32560  0.187203       0.533333      0.150242           0.0        0.397959

[32561 rows x 5 columns]

In [17]:
scaler = StandardScaler()
df_standardized = pd.DataFrame(scaler.fit_transform(ndf), columns=ndf.columns)

print("Standardized Data:")
print(df_standardized)

Standardized Data:
         fnlwgt  education-num  capital-gain  capital-loss  hours-per-week
0     -1.063611       1.134739      0.148453      -0.21666       -0.035429
1     -1.008707       1.134739     -0.145920      -0.21666       -2.222153
2      0.245079      -0.420060     -0.145920      -0.21666       -0.035429
3      0.425801      -1.197459     -0.145920      -0.21666       -0.035429
4      1.408176       1.134739     -0.145920      -0.21666       -0.035429
...         ...            ...           ...           ...             ...
32556  0.639741       0.746039     -0.145920      -0.21666       -0.197409
32557 -0.335433      -0.420060     -0.145920      -0.21666       -0.035429
32558 -0.358777      -0.420060     -0.145920      -0.21666       -0.035429
32559  0.110960      -0.420060     -0.145920      -0.21666       -1.655225
32560  0.929893      -0.420060      1.888424      -0.21666       -0.035429

[32561 rows x 5 columns]

# Lets apply:
* **MinMax**: 'fnlwgt' 'capital-gain' 'capital-loss'

* **Z-score**: 'hours-per-week'

* **Do not normalization**: 'education-num'

In [27]:
scaler = MinMaxScaler()

df[['fnlwgt_norm','capital-gain_norm','capital-loss_norm']] = pd.DataFrame(scaler.fit_transform(df[['fnlwgt','capital-gain','capital-loss']]), columns=['fnlwgt','capital-gain','capital-loss'])

In [38]:
scaler = StandardScaler()
hours_per_week_2d = df['hours-per-week'].values.reshape(-1, 1)
df['hours-per-week_norm'] = pd.DataFrame(scaler.fit_transform(hours_per_week_2d))

In [40]:
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income,fnlwgt_norm,capital-gain_norm,capital-loss_norm,hours-per-week_norm
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,0.044302,0.021740,0.0,-0.035429
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,0.048238,0.000000,0.0,-2.222153
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,0.138113,0.000000,0.0,-0.035429
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,0.151068,0.000000,0.0,-0.035429
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,0.221488,0.000000,0.0,-0.035429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K,0.166404,0.000000,0.0,-0.197409
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K,0.096500,0.000000,0.0,-0.035429
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K,0.094827,0.000000,0.0,-0.035429
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K,0.128499,0.000000,0.0,-1.655225
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K,0.187203,0.150242,0.0,-0.035429

In [42]:
outliers1 = df[(df['hours-per-week_norm'] > 3)|(df['hours-per-week_norm'] < -3)]

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income,fnlwgt_norm,capital-gain_norm,capital-loss_norm,hours-per-week_norm
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K,0.182135,0.0,0.000000,3.204161
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K,0.241083,0.0,0.000000,3.204161
77,67,?,212759,10th,6,Married-civ-spouse,?,Husband,White,Male,0,0,2,United-States,<=50K,0.136153,0.0,0.000000,-3.113041
157,71,Self-emp-not-inc,494223,Some-college,10,Separated,Sales,Unmarried,Black,Male,0,1816,2,United-States,<=50K,0.327310,0.0,0.416896,-3.113041
189,58,State-gov,109567,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,1,United-States,>50K,0.066069,0.0,0.000000,-3.194030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32469,58,Self-emp-inc,181974,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,99,?,<=50K,0.115245,0.0,0.000000,4.742967
32476,35,Private,30673,12th,8,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,84,United-States,<=50K,0.012488,0.0,0.000000,3.528120
32494,82,?,403910,HS-grad,9,Never-married,?,Not-in-family,White,Male,0,0,3,United-States,<=50K,0.265974,0.0,0.000000,-3.032051
32525,81,?,120478,Assoc-voc,11,Divorced,?,Unmarried,White,Female,0,0,1,?,<=50K,0.073480,0.0,0.000000,-3.194030
32531,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K,0.014619,0.0,0.000000,4.742967

In [50]:
Q1 = df['capital-loss_norm'].quantile(0.25)
Q3 = df['capital-loss_norm'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers2 = df[(df['capital-loss_norm'] < lower_bound) | (df['capital-loss_norm'] > upper_bound)]
outliers2

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income,fnlwgt_norm,capital-gain_norm,capital-loss_norm,hours-per-week_norm
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K,0.071143,0.0,0.468779,-0.035429
32,45,Private,386940,Bachelors,13,Divorced,Exec-managerial,Own-child,White,Male,0,1408,40,United-States,<=50K,0.254448,0.0,0.323232,-0.035429
52,47,Private,51835,Prof-school,15,Married-civ-spouse,Prof-specialty,Wife,White,Female,0,1902,60,Honduras,>50K,0.026861,0.0,0.436639,1.584366
93,30,Private,117747,HS-grad,9,Married-civ-spouse,Sales,Wife,Asian-Pac-Islander,Female,0,1573,35,?,<=50K,0.071625,0.0,0.361111,-0.440378
96,48,Self-emp-not-inc,191277,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,1902,60,United-States,>50K,0.121563,0.0,0.436639,1.584366
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32441,53,Private,304504,Some-college,10,Married-civ-spouse,Transport-moving,Husband,White,Male,0,1887,45,United-States,>50K,0.198462,0.0,0.433196,0.369519
32443,18,Private,41381,HS-grad,9,Never-married,Sales,Own-child,White,Female,0,1602,20,United-States,<=50K,0.019761,0.0,0.367769,-1.655225
32445,61,Private,190682,HS-grad,9,Widowed,Craft-repair,Not-in-family,Black,Female,0,1669,50,United-States,<=50K,0.121159,0.0,0.383150,0.774468
32458,36,Private,237943,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,1977,45,United-States,>50K,0.153257,0.0,0.453857,0.369519
32500,34,Private,60567,11th,7,Divorced,Transport-moving,Unmarried,White,Male,0,880,60,United-States,<=50K,0.032791,0.0,0.202020,1.584366

In [51]:
print(Q1)
print(Q3)
print(IQR)

0.0
0.0
0.0

Searching for outliers in columns 'capital gain' and 'capital loos' does not matter, since more than half of the values are zero