<a href="https://colab.research.google.com/github/dkuzzmin/DI-Bootcamp/blob/main/Week4/Day4/Day4_XC_XP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Exercises from day learning**

In [6]:
import pandas as pd

In [70]:
df = pd.read_csv('electronics.csv')
df

,Unnamed: 0,Name,Age,Product Purchased,Price,Date,Warranty
0,0,James Wilson,21.0,E-reader,250,2022-02-10,3 years
1,1,Margaret King,59.0,Camera,700,2022-03-22,NaN
2,2,David Walker,53.0,Laptop,800,2022-09-06,2 years
3,3,James Wilson,65.0,Camera,700,2022-02-22,2 years
4,4,Joseph Hall,63.0,Headphones,100,2022-12-14,NaN
5,5,Emily Davis,50.0,Camera,700,2022-03-30,2 years
6,6,Susan Lee,36.0,NaN,250,2022-02-05,3 years
7,7,Jennifer Clark,42.0,NaN,250,2022-08-25,NaN
8,8,Michael Brown,40.0,Speakers,150,2022-04-15,NaN
9,9,Barbara Jones,25.0,Headphones,100,2022-11-14,NaN
10,10,Sarah Johnson,NaN,Laptop,800,2022-03-15,3 years
11,11,Maria Lewis,30.0,Speakers,150,2022-08-26,3 years
12,12,Maria Lewis,48.0,Smartphone,600,2022-11-17,2 years
13,13,Robert Harris,41.0,Smartwatch,250,2022-09-02,NaN
14,14,Barbara Jones,45.0,Speakers,150,2022-04-02,2 years
15,15,Olivia Martin,49.0,Smartphone,600,2022-01-27,2 years
16,16,John Doe,40.0,E-reader,250,2022-09-06,1 year
17,17,Susan Lee,25.0,Smartphone,600,2022-02-13,2 years
18,18,Maria Lewis,44.0,Tablet,400,NaN,NaN
19,19,Susan Lee,44.0,Camera,700,2022-04-08,3 years

Remove years from warranty column - make it an integer, to allow us to graph/measure the data in that column.

Fill in missing prices based on similar/identical products (Product and Price)

Maybe find missing ages based on Name of customer. If not, fill with median age.

(Potentially drop rows with missing names. Based on the specific)

Fill in missing waranties with 0.

In [71]:
# for i in range(len(df)):
#     # print(df.iloc[i]['Warranty'])
#    if type(df.iloc[i]['Warranty']) == str:
#       df.iloc[i]['Warranty'] = df.iloc[i]['Warranty'].replace(' years','')
#    if type(df.iloc[i]['Warranty']) == str:
#       df.iloc[i]['Warranty'] = df.iloc[i]['Warranty'].replace(' year','')

df["Warranty"] = df["Warranty"].str.replace(' years','')
df["Warranty"] = df["Warranty"].str.replace(' year','')
df

,Unnamed: 0,Name,Age,Product Purchased,Price,Date,Warranty
0,0,James Wilson,21.0,E-reader,250,2022-02-10,3
1,1,Margaret King,59.0,Camera,700,2022-03-22,NaN
2,2,David Walker,53.0,Laptop,800,2022-09-06,2
3,3,James Wilson,65.0,Camera,700,2022-02-22,2
4,4,Joseph Hall,63.0,Headphones,100,2022-12-14,NaN
5,5,Emily Davis,50.0,Camera,700,2022-03-30,2
6,6,Susan Lee,36.0,NaN,250,2022-02-05,3
7,7,Jennifer Clark,42.0,NaN,250,2022-08-25,NaN
8,8,Michael Brown,40.0,Speakers,150,2022-04-15,NaN
9,9,Barbara Jones,25.0,Headphones,100,2022-11-14,NaN
10,10,Sarah Johnson,NaN,Laptop,800,2022-03-15,3
11,11,Maria Lewis,30.0,Speakers,150,2022-08-26,3
12,12,Maria Lewis,48.0,Smartphone,600,2022-11-17,2
13,13,Robert Harris,41.0,Smartwatch,250,2022-09-02,NaN
14,14,Barbara Jones,45.0,Speakers,150,2022-04-02,2
15,15,Olivia Martin,49.0,Smartphone,600,2022-01-27,2
16,16,John Doe,40.0,E-reader,250,2022-09-06,1
17,17,Susan Lee,25.0,Smartphone,600,2022-02-13,2
18,18,Maria Lewis,44.0,Tablet,400,NaN,NaN
19,19,Susan Lee,44.0,Camera,700,2022-04-08,3

In [72]:
df['Warranty'][df['Warranty'].isna()] = 0
df["Warranty"] = df["Warranty"].astype(int)
df

<ipython-input-72-71fa6c038850>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Warranty'][df['Warranty'].isna()] = 0

,Unnamed: 0,Name,Age,Product Purchased,Price,Date,Warranty
0,0,James Wilson,21.0,E-reader,250,2022-02-10,3
1,1,Margaret King,59.0,Camera,700,2022-03-22,0
2,2,David Walker,53.0,Laptop,800,2022-09-06,2
3,3,James Wilson,65.0,Camera,700,2022-02-22,2
4,4,Joseph Hall,63.0,Headphones,100,2022-12-14,0
5,5,Emily Davis,50.0,Camera,700,2022-03-30,2
6,6,Susan Lee,36.0,NaN,250,2022-02-05,3
7,7,Jennifer Clark,42.0,NaN,250,2022-08-25,0
8,8,Michael Brown,40.0,Speakers,150,2022-04-15,0
9,9,Barbara Jones,25.0,Headphones,100,2022-11-14,0
10,10,Sarah Johnson,NaN,Laptop,800,2022-03-15,3
11,11,Maria Lewis,30.0,Speakers,150,2022-08-26,3
12,12,Maria Lewis,48.0,Smartphone,600,2022-11-17,2
13,13,Robert Harris,41.0,Smartwatch,250,2022-09-02,0
14,14,Barbara Jones,45.0,Speakers,150,2022-04-02,2
15,15,Olivia Martin,49.0,Smartphone,600,2022-01-27,2
16,16,John Doe,40.0,E-reader,250,2022-09-06,1
17,17,Susan Lee,25.0,Smartphone,600,2022-02-13,2
18,18,Maria Lewis,44.0,Tablet,400,NaN,0
19,19,Susan Lee,44.0,Camera,700,2022-04-08,3

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         20 non-null     int64
 1   Name               20 non-null     object
 2   Age                19 non-null     float64
 3   Product Purchased  18 non-null     object
 4   Price              20 non-null     int64
 5   Date               19 non-null     object
 6   Warranty           20 non-null     int64
dtypes: float64(1), int64(3), object(3)
memory usage: 1.2+ KB

In [109]:
import numpy as np
df.Price[df['Name'] == 'John Doe'] = np.nan

<ipython-input-109-ba34e88dd53a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Price[df['Name'] == 'John Doe'] = np.nan

In [110]:
df

,Unnamed: 0,Name,Age,Product Purchased,Price,Date,Warranty
0,0,James Wilson,21.0,E-reader,250.0,2022-02-10,3
1,1,Margaret King,59.0,Camera,700.0,2022-03-22,0
2,2,David Walker,53.0,Laptop,800.0,2022-09-06,2
3,3,James Wilson,65.0,Camera,700.0,2022-02-22,2
4,4,Joseph Hall,63.0,Headphones,100.0,2022-12-14,0
5,5,Emily Davis,50.0,Camera,700.0,2022-03-30,2
6,6,Susan Lee,36.0,NaN,250.0,2022-02-05,3
7,7,Jennifer Clark,42.0,NaN,250.0,2022-08-25,0
8,8,Michael Brown,40.0,Speakers,150.0,2022-04-15,0
9,9,Barbara Jones,25.0,Headphones,100.0,2022-11-14,0
10,10,Sarah Johnson,NaN,Laptop,800.0,2022-03-15,3
11,11,Maria Lewis,30.0,Speakers,150.0,2022-08-26,3
12,12,Maria Lewis,48.0,Smartphone,600.0,2022-11-17,2
13,13,Robert Harris,41.0,Smartwatch,250.0,2022-09-02,0
14,14,Barbara Jones,45.0,Speakers,150.0,2022-04-02,2
15,15,Olivia Martin,49.0,Smartphone,600.0,2022-01-27,2
16,16,John Doe,40.0,E-reader,NaN,2022-09-06,1
17,17,Susan Lee,25.0,Smartphone,600.0,2022-02-13,2
18,18,Maria Lewis,44.0,Tablet,400.0,NaN,0
19,19,Susan Lee,44.0,Camera,700.0,2022-04-08,3

In [88]:
df[df['Product Purchased'] == 'E-reader']

,Unnamed: 0,Name,Age,Product Purchased,Price,Date,Warranty,Product Purchaesd
0,0,James Wilson,21.0,E-reader,250.0,2022-02-10,3,E-reader
16,16,John Doe,40.0,E-reader,NaN,2022-09-06,1,E-reader

In [98]:
df.drop('Product Purchaesd', axis=1, inplace=True)

In [100]:
df[df['Product Purchased'] == 'E-reader']

,Unnamed: 0,Name,Age,Product Purchased,Price,Date,Warranty
0,0,James Wilson,21.0,E-reader,250.0,2022-02-10,3
16,16,John Doe,40.0,E-reader,NaN,2022-09-06,1

In [111]:
df['Price'].loc[16] = 250

<ipython-input-111-1d9e12b09990>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Price'].loc[16] = 250

In [112]:
df

,Unnamed: 0,Name,Age,Product Purchased,Price,Date,Warranty
0,0,James Wilson,21.0,E-reader,250.0,2022-02-10,3
1,1,Margaret King,59.0,Camera,700.0,2022-03-22,0
2,2,David Walker,53.0,Laptop,800.0,2022-09-06,2
3,3,James Wilson,65.0,Camera,700.0,2022-02-22,2
4,4,Joseph Hall,63.0,Headphones,100.0,2022-12-14,0
5,5,Emily Davis,50.0,Camera,700.0,2022-03-30,2
6,6,Susan Lee,36.0,NaN,250.0,2022-02-05,3
7,7,Jennifer Clark,42.0,NaN,250.0,2022-08-25,0
8,8,Michael Brown,40.0,Speakers,150.0,2022-04-15,0
9,9,Barbara Jones,25.0,Headphones,100.0,2022-11-14,0
10,10,Sarah Johnson,NaN,Laptop,800.0,2022-03-15,3
11,11,Maria Lewis,30.0,Speakers,150.0,2022-08-26,3
12,12,Maria Lewis,48.0,Smartphone,600.0,2022-11-17,2
13,13,Robert Harris,41.0,Smartwatch,250.0,2022-09-02,0
14,14,Barbara Jones,45.0,Speakers,150.0,2022-04-02,2
15,15,Olivia Martin,49.0,Smartphone,600.0,2022-01-27,2
16,16,John Doe,40.0,E-reader,250.0,2022-09-06,1
17,17,Susan Lee,25.0,Smartphone,600.0,2022-02-13,2
18,18,Maria Lewis,44.0,Tablet,400.0,NaN,0
19,19,Susan Lee,44.0,Camera,700.0,2022-04-08,3

In [117]:
df[df['Name'] == 'Sarah Johnson']

,Unnamed: 0,Name,Age,Product Purchased,Price,Date,Warranty
10,10,Sarah Johnson,NaN,Laptop,800.0,2022-03-15,3

We dont have another purchaces of this customer, so we will assign an average age

In [122]:
df['Age'].loc[10] = df['Age'].mean().astype(int)

<ipython-input-122-f3fc7f5e61f5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'].loc[10] = df['Age'].mean().astype(int)

In [123]:
df

,Unnamed: 0,Name,Age,Product Purchased,Price,Date,Warranty
0,0,James Wilson,21.0,E-reader,250.0,2022-02-10,3
1,1,Margaret King,59.0,Camera,700.0,2022-03-22,0
2,2,David Walker,53.0,Laptop,800.0,2022-09-06,2
3,3,James Wilson,65.0,Camera,700.0,2022-02-22,2
4,4,Joseph Hall,63.0,Headphones,100.0,2022-12-14,0
5,5,Emily Davis,50.0,Camera,700.0,2022-03-30,2
6,6,Susan Lee,36.0,NaN,250.0,2022-02-05,3
7,7,Jennifer Clark,42.0,NaN,250.0,2022-08-25,0
8,8,Michael Brown,40.0,Speakers,150.0,2022-04-15,0
9,9,Barbara Jones,25.0,Headphones,100.0,2022-11-14,0
10,10,Sarah Johnson,43.0,Laptop,800.0,2022-03-15,3
11,11,Maria Lewis,30.0,Speakers,150.0,2022-08-26,3
12,12,Maria Lewis,48.0,Smartphone,600.0,2022-11-17,2
13,13,Robert Harris,41.0,Smartwatch,250.0,2022-09-02,0
14,14,Barbara Jones,45.0,Speakers,150.0,2022-04-02,2
15,15,Olivia Martin,49.0,Smartphone,600.0,2022-01-27,2
16,16,John Doe,40.0,E-reader,250.0,2022-09-06,1
17,17,Susan Lee,25.0,Smartphone,600.0,2022-02-13,2
18,18,Maria Lewis,44.0,Tablet,400.0,NaN,0
19,19,Susan Lee,44.0,Camera,700.0,2022-04-08,3

**🌟 Exercise 1: Duplicate Detection And Removal**

In [124]:
import pandas as pd

In [125]:
df = pd.read_csv('tested.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [132]:
df[df.duplicated()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [ ]:
We dont have duplicated data

** Exercise 2: Handling Missing Values**

In [137]:
df[df['Name'].isna()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [138]:
df[df['Sex'].isna()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [139]:
df[df['Cabin'].isna()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
412,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C