<a href="https://colab.research.google.com/github/dkuzzmin/DI-Bootcamp/blob/main/Week4/Day4/W4Day4_XC_DC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [69]:
df = pd.read_csv("/content/datascience_salaries.csv")

In [70]:
df

,Unnamed: 0,job_title,job_type,experience_level,location,salary_currency,salary
0,0,Data scientist,Full Time,Senior,New York City,USD,149000
1,2,Data scientist,Full Time,Senior,Boston,USD,120000
2,3,Data scientist,Full Time,Senior,London,USD,68000
3,4,Data scientist,Full Time,Senior,Boston,USD,120000
4,5,Data scientist,Full Time,Senior,New York City,USD,149000
...,...,...,...,...,...,...,...
1166,2243,ML Ops,Full Time,Senior,Toronto,USD,228000
1167,2249,ML Ops,Full Time,Senior,Boston,USD,115000
1168,2250,ML Ops,Full Time,Senior,Delhi,USD,76000
1169,2255,ML Ops,Full Time,Senior,San Francisco,USD,68000
1170,2259,ML Ops,Internship,Senior,New York City,USD,135000

**Let's make a column with salaries in USD**

In [13]:
df['salary_currency'].unique()

array(['USD', 'EUR', 'GBP'], dtype=object)

In [75]:
df1 = df[df['salary_currency'] == 'GBP']['salary'] * 1.27
df2 = df[df['salary_currency'] == 'EUR']['salary'] * 1.10
df3 = df[df['salary_currency'] == 'USD']['salary']
df_usd = pd.concat([df1, df2, df3])
df['salary_in_usd'] = df_usd
df[newdf['salary_currency'] == 'EUR']

,Unnamed: 0,job_title,job_type,experience_level,location,salary_currency,salary,salary_in_usd
63,84,Data scientist,Full Time,Senior,Madrid,EUR,36000,39600.0
94,123,Data scientist,Full Time,Mid,Paris,EUR,50000,55000.0
149,188,Data scientist,Full Time,Senior,Madrid,EUR,36000,39600.0
182,226,Data scientist,Full Time,Mid,Berlin,EUR,58000,63800.0
238,295,Data scientist,Full Time,Senior,Madrid,EUR,36000,39600.0
354,444,Data scientist,Full Time,Senior,Madrid,EUR,36000,39600.0
421,537,Data analyst,Full Time,Senior,Madrid,EUR,38000,41800.0
762,1200,Big data,Full Time,Senior,Remote,EUR,65000,71500.0
1008,1800,Machine learning,Full Time,Senior,Paris | Remote,EUR,70000,77000.0

**Normalize the â€˜salaryâ€™ column using Min-Max normalization.**

In [76]:
df['salary_norm'] = (df['salary_in_usd'] - df['salary_in_usd'].min())/(df['salary_in_usd'].max() - df['salary_in_usd'].min())

In [77]:
df.sample(20)

,Unnamed: 0,job_title,job_type,experience_level,location,salary_currency,salary,salary_in_usd,salary_norm
473,627,Data analyst,Full Time,Mid,London,USD,51000,51000.0,0.106061
303,375,Data scientist,Full Time,Senior,Tel Aviv-Yafo,USD,68000,68000.0,0.191919
894,1534,Machine learning,Full Time,Senior,United States (Remote),USD,45000,45000.0,0.075758
217,266,Data scientist,Full Time,Senior,Bangkok,USD,68000,68000.0,0.191919
507,683,Data analyst,Full Time,Senior,Pittsburgh,USD,63000,63000.0,0.166667
278,348,Data scientist,Full Time,Mid,Roppongi,USD,62000,62000.0,0.161616
76,99,Data scientist,Full Time,Entry,Palaiseau,USD,36000,36000.0,0.030303
517,708,Data analyst,Full Time,Mid,Arlington,USD,51000,51000.0,0.106061
433,561,Data analyst,Full Time,Senior,Washington,USD,81000,81000.0,0.257576
679,959,Data analyst,Full Time,Mid,Fremont,USD,51000,51000.0,0.106061
1052,1896,Machine learning,Full Time,Senior,Canada,USD,45000,45000.0,0.075758
57,78,Data scientist,Full Time,Senior,Salt Lake City,USD,68000,68000.0,0.191919
664,939,Data analyst,Full Time,Mid,Paris,USD,51000,51000.0,0.106061
164,206,Data scientist,Full Time,Senior,Berlin,USD,120000,120000.0,0.454545
1055,1911,Machine learning,Full Time,Mid,Bengaluru,USD,63000,63000.0,0.166667
660,933,Data analyst,Full Time,Senior,Canada,USD,63000,63000.0,0.166667
910,1558,Machine learning,Full Time,Senior,United States,USD,45000,45000.0,0.075758
967,1695,Machine learning,Full Time,Mid,United States - Remote,USD,43000,43000.0,0.065657
310,384,Data scientist,Full Time,Senior,Dallas,USD,68000,68000.0,0.191919
1069,1949,Machine learning,Full Time,Mid,South Jakarta,USD,43000,43000.0,0.065657

**Implement dimensionality reduction on the dataset.**

In [83]:
df_new = df.copy()
df_new['salary'] = df_new['salary']/1000
df_new['salary_in_usd'] = df_new['salary_in_usd']/1000
df_new

,Unnamed: 0,job_title,job_type,experience_level,location,salary_currency,salary,salary_in_usd,salary_norm
0,0,Data scientist,Full Time,Senior,New York City,USD,149.0,149.0,0.601010
1,2,Data scientist,Full Time,Senior,Boston,USD,120.0,120.0,0.454545
2,3,Data scientist,Full Time,Senior,London,USD,68.0,68.0,0.191919
3,4,Data scientist,Full Time,Senior,Boston,USD,120.0,120.0,0.454545
4,5,Data scientist,Full Time,Senior,New York City,USD,149.0,149.0,0.601010
...,...,...,...,...,...,...,...,...,...
1166,2243,ML Ops,Full Time,Senior,Toronto,USD,228.0,228.0,1.000000
1167,2249,ML Ops,Full Time,Senior,Boston,USD,115.0,115.0,0.429293
1168,2250,ML Ops,Full Time,Senior,Delhi,USD,76.0,76.0,0.232323
1169,2255,ML Ops,Full Time,Senior,San Francisco,USD,68.0,68.0,0.191919
1170,2259,ML Ops,Internship,Senior,New York City,USD,135.0,135.0,0.530303

**Aggregate data by â€˜experience_levelâ€™, calculating average and median salaries.**

In [86]:
agg_data = df_new.groupby('experience_level')['salary_in_usd'].agg(['mean', 'median'])

In [85]:
agg_data

                       mean  median
experience_level
Entry             36.111111    30.0
Executive         76.076923    46.0
Mid               51.786885    51.0
Senior            75.088033    68.0